code/game/verbs/emotions.dm
Нерабочие эмоуты удалены. Остальные вполне работают.
=> Вкладка эмоутов. Не переведено на русский.

code/game/verbs/ooc.dm
=> need for test

code/modules/admin/admin.dm
=> Initial fux

baystation12.dme
=> Таки вырубил вкладку эмутов на бее по прозьбе создателя в связи с их устареванием.

interface/interface.dm
- Исправление Travis-Ci, оптимизация функции вывода контента клиенту в файле interface/interface.dm
- @S-Spy, посмотри пожалуйста список макросов baystation12 в файле code/_macros.dm, в репозитории baystation не уместно использовать для вывода текста/другой информации операторы `<<` `>>`
- @bear1ake, хош вернусь?
- @seekin4u, я должен тебе пиво.
=> Замена оператора << в interface/interface.dm

interface/skin.dmf
- Фикс интерфейса, чейнжлог сами пишите... Зачем я этим говном занялся вообще? Не нужно мне кодить.
- Здесь был Френсис и он ненавидит вертолёты.
=> interface fix

code/game/turfs/turf.dm, code/modules/awaymissions/zlevel.dm, code/modules/mining/mine_turfs.dm, code/world.dm
**Просьба для мэинтейнеров ТЩАТЕЛЬНО проверить астероид и освещение на нем!!!**
Ну, в идеале, саму работу тоже стоит нормально проверить. Рантаймов нет, поверхностных багов нет.
=> Ускоряет запуск билда примерно в 2.5-3 раза.

code/modules/mob/language/station.dm
Убирает необходимость наличия вайтлиста изначально присутствующего только у людей, на язык Sol Common
=> Снятие необходимости вайтлиста с Sol common

code/modules/tables/rack.dm, code/modules/tables/tables.dm
Исправлена недоработка с выпадением пластика из rack'ов.
Исправлена недоработка с отображением спрайтов столов, если несколько раз тыкать материалами при сборке.
=> Фикс столов и rack'ов.

code/modules/clothing/head/misc.dm
- Теперь хиджаб прячет только волосы на голове, оставляя растительность на лице.
=> from blockhair to blockheadhair

code/modules/power/lighting.dm
- Теперь сборка ламп начинается с первого шага а не второго.
=> light fixture fix

code/modules/mob/living/carbon/human/species/station/machine.dm
=> Увеличение кол-ва доступных к выбору языков для СПУ

code/modules/mob/living/simple_animal/hostile/hivebot.dm
=> Доработка хайвботов и реализация некоторых фич.

code/modules/mob/living/carbon/human/species/station/resomi.dm
Баланс скорости Резоми изменён на "желаемый" уровень, вам лишь осталось нажать одну кнопку.
=> Попытка номер два.

code/modules/mob/living/carbon/human/species/station/station.dm, html/changelogs_infinity/sladkoeshka-kobortor_moh.yml
=> Вайтлист на таяр и ящуров

maps/torch/infinity_station_maps/torch-2.dmm
=> Добавляем книги по инженерному делу в библиотеку.

maps/torch/loadout/loadout_xeno.dm
=> Добавляем маленькое "пальто" в лодаут резоми.

code/game/objects/items/devices/boombox.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/topic.dm
=> Boombox Panel update

code/__defines/misc.dm, code/game/turfs/simulated/floor.dm, code/game/turfs/turf.dm, code/game/turfs/turf_ao.dm
<details>
</details>
<details>
</details>
<details>
</details>
=> Bring AO back with new fixes from EuropaStation

code/__defines/chemistry.dm
Возвращаем поварам цену работы
=> Возвращаем старое значение для уменьшения голода

baystation12.dme, code/_helpers/global_access.dm, code/game/turfs/flooring/flooring_decals.dm, code/game/turfs/flooring/flooring_premade.dm, code/game/turfs/simulated/floor.dm, code/game/turfs/space/space.dm, code/game/turfs/turf_ao.dm, code/game/turfs/turf_changing.dm, code/game/turfs/unsimulated/beach.dm
На всякий случай код всё ещё будет в отдельном файлике.
=> Убираем AO из процесса компиляции

code/game/atoms_movable.dm, config/config.txt
Это почти самые рекомендуемые, так как они по умолчанию.
=> Тестовые параметры тиклага и фпс

code/modules/lighting/lighting_corner.dm, code/modules/lighting/lighting_source.dm, code/modules/power/lighting.dm
Выглядит так же красиво, не напрягает глаза.
=> Возвращаем старые настройки света без изменения цвета

code/modules/clothing/infinity_clothing/glasses.dm, code/modules/research/designs.dm
- Запилены обычные материал-велдинг гибридки
- Гибридки добавлены в РнД
Планируется добавить больше гибридных очков в РнД и понерфать "специальные" очки Николаса, но это уже в следующем пулле.
=> Реквест очков 2: Электрическое Бугало

config/custom_items.txt
На то время, когда кто-то все таки решит дать данному человеку данную кастомку.
_**Желательно не пуллить раньше, чем #113.**_
=> Кастомка для Николаса

maps/torch/infinity_station_maps/torch-5.dmm
- Интеркомы теперь находятся в удобной близости от офисного стола главы.
- При желании ИИ теперь может легко подслушивать разговоры.
- Главы теперь могут легко и просто дотянуться до интеркома в случаи потери стандартной связи.
=> Улучшение кабинетов глав: удобные интеркомы.

code/_onclick/other_mobs.dm, code/modules/mob/living/simple_animal/familiars/familiars.dm
Конструкты снова могут убивать!
Теперь вы снова можете встать если легли за фамильяра мага.
=> Фиксы простых мобов

code/modules/projectiles/guns/launcher/money_cannon.dm
Пушка больше не будет стрелять пустотой
=> Фикс денежной пушки

code/game/objects/structures/crates_lockers/closets/walllocker.dm
Теперь при закрытии он не будет мешать перемещаться по тайлу на котором он расположен.
=> Фикс настенного шкафчика.

code/modules/mob/living/carbon/human/species/species.dm
Возможность людям и ксеносам гладить друг-друга по голове и пожимать руку, если она имеется.
=> Пожмем руку и погладим по голове.

code/modules/reagents/Chemistry-Machinery.dm
=>  Заменяем проверку скилла на проверку брейндамага у гриндера

code/modules/reagents/reagent_containers/glass/bottle.dm
=> Добавляем бутылочки с триком и периксадоном.

code/game/atoms.dm, code/game/atoms_movable.dm, code/game/objects/items.dm, code/game/objects/objs.dm, code/game/sound.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/mob_defines.dm, code/modules/multiz/movement.dm, code/modules/power/singularity/singularity.dm, code/modules/shuttles/shuttle.dm
now you can get hit from object
increase throw speed on shuttles
lower throw speed for humans
=> throw changes

maps/sierra/datums/reports.dm
- "ИО" заменено на "ГП"
- лёгкие коррекции в коде и тексте для улучшения читабельности
=> Коррекции в формах для Report Editor

code/modules/modular_computers/computers/subtypes/dev_wrist.dm
* По умолчанию выключены.
* Можно взаимодействовать в надетом состоянии.
* Перетащить на себя для снятия.
=> Небольшое изменение для наручных компьютеров

maps/sierra/items/headsets.dm
жесть ребята я так устал пока это фиксил...
https://github.com/infinitystation/Baystation12/issues/400
=> разработочка

code/game/machinery/deployable.dm, code/game/objects/structures/barrier.dm, code/game/objects/structures/door_assembly.dm, code/game/objects/structures/girders.dm, code/game/objects/structures/railing.dm, code/modules/tables/tables.dm
Теперь агрессивные мобы снова должны нормально ломать некоторые объекты.
=> Фикс разрушения объектов

html/changelogs_infinity/coltrane97-medbaystorage
=> Чейнджлог.

baystation12.dme, code/modules/mob/living/bot/bot.dm, code/modules/mob/living/bot/bot_damage.dm
Что нового:
* Станционные боты (например клинер или офицерский бот) теперь снова подвергаются огню и физическому урону
=> Исправление бессмертия станционных ботов

code/modules/reagents/reagent_containers/food/cans.dm, code/modules/reagents/reagent_containers/food/drinks.dm, code/modules/reagents/reagent_containers/food/drinks/bottle.dm
Что нового:
* [Портирована механика питья залпом с Эриса](https://github.com/discordia-space/CEV-Eris/pull/2227) с некоторыми незначительными изменениями
* Отменено изменение, связанное с выводимым сообщением и звуком питья в зависимости от количества выпитой жидкости за раз. Теперь звуки используются в новой механике
* Отменено изменение, связанное с возможностью менять количество при переливании жидкости для напитков и банок
=> [Port] Drinking it all up mechanic

code/game/objects/noose.dm
Что нового:
* Немного пробежался по коду и обновил его
* Теперь помимо кусачек, любой острый предмет может разорвать петлю
=> Небольшие изменения петли

code/modules/clothing/infinity_clothing/accessory.dm, maps/sierra/loadout/loadout_accessories.dm
Разрешен конфликт между значками бэя и догтэгами.
=> Трэвис и значки

code/_helpers/text.dm, code/controllers/evacuation/evacuation.dm, code/controllers/evacuation/evacuation_lifepods.dm, code/controllers/evacuation/evacuation_pods.dm, code/controllers/evacuation/evacuation_shuttle.dm, code/controllers/subsystems/ticker.dm
=> Cold-фикс конца раунда при крю-трансфере

code/modules/mob/living/silicon/robot/robot_modules.dm
Убираем лишнюю монтировку у крайзиз киборга.
=> Одна монтировка на рыло.

code/game/objects/items/devices/scanners.dm
Вместо 03:00 на сканнерах будет показывать настоящее время смерти.
=> Фикс даты смерти.

code/game/machinery/Sleeper.dm
Улучшение слипера с возможностью получения новых лекарств.
В балансе не силен, но:
Без серебра будет максимум лишь второй уровень синтезов. А именно это добавляет:
[Inaprovaline, Soporific, **Tramadol**, Dylovene, **Hyronalin**, Dexalin, **Kelotane**]
С серебром же уже можно будет сделать третий уровень. Это же:
[Inaprovaline, Soporific, Tramadol, Dylovene, **Arithrazine**, **Dexalin Plus**, **Dermaline**, **Bicaridine**, **Alkysine**]
=> Sleepers UP

maps/torchinf/loadout/loadout_accessories.dm, maps/torchinf/loadout/loadout_eyes.dm, maps/torchinf/loadout/loadout_gloves.dm, maps/torchinf/loadout/loadout_head.dm, maps/torchinf/loadout/loadout_infinity.dm, maps/torchinf/loadout/loadout_infinity_tact.dm, maps/torchinf/loadout/loadout_shoes.dm, maps/torchinf/loadout/loadout_suit.dm, maps/torchinf/loadout/loadout_uniform.dm, maps/torchinf/loadout/loadout_xeno.dm
:cl:
rscadd: Большая часть гражданских айтемов может быть взята даже военными.
/:cl:
=> Лодаут торча без ограничений на 50%

code/modules/surgery/generic.dm
Давайте не будем резать друг-другу кости, ладненько? 
close #607
=> Подтверждение при ампутации конечности.

code/modules/research/rdconsole.dm
Фикс аналогичен тому же, что и биогенератору.
=> Небольшой фикс протолата. 

code/game/machinery/biogenerator.dm
При апгрейде показывает актуальную цену.
=> Небольшой фикс биогенератора. 

code/game/objects/structures/wall_frame.dm
=> Небольшой фикс по разборке низкой стены.

code/modules/mob/living/carbon/resist.dm
**Господи, как же я долго ждал этот фикс.**
close #263
=> Убираем стан при вставании со стулов с помощью резиста.

code/modules/species/station/station.dm
=> Починил проверку на пол для скреллов. 

code/modules/species/station/adherent.dm
=> Небольшие фиксы Адхерантов. 

code/game/objects/items/weapons/storage/storage.dm
=> Перестаем видеть во сне\в отключке кто и что куда перекладывает.

code/game/verbs/sound.dm
=> Починил Stop all sounds.

code/modules/species/station/machine.dm
close #659 
Ну кусать то они не могут.. Верно же?
=> Обучаем ИПК приемам из кунг-фу.

code/modules/modular_computers/computers/modular_computer/interaction.dm
=> Забираем способность телепортировать карточки из компьютера у ИИ и роботов.

code/modules/projectiles/guns/projectile/automatic.dm
=> Выдаем предохранители пушечкам. 

baystation12.dme, code/game/objects/items/devices/multimeter.dm, code/modules/clothing/chameleon.dm, code/modules/research/designs.dm, code/modules/research/infinity_designs.dm
- Новые технологии для создания в протолате:
- flora data disk. 
- bluespace rapid part exchange device.
- health analyzer.
- plant analyzer. 
- defibrillator. 
- compact defibrillator.
- rapid pipe dispenser. 
- powersink. **[illegal]**
- Поправил Material Glasses и Trashbag of holding, которые не появлялись в списке из-за опечаток. 
- Исправил порядок сортировки. 
- Все названия дизайнов теперь с маленькой, ибо с большой это выглядит отвратно. 
- Chameleon Kit требует теперь третий уровень нелегальных исследований.
- Chameleon Revolver теряет свой имбовый (TECH_ILLEGAL = 8). Да простит меня господь за это.
=> Поправки в дизайнах протолата. 

code/game/objects/items/weapons/storage/belt.dm
=> More space for tactical belt

code/game/objects/items/stacks/medical.dm
Бинты дупаются таким путём: "Берём в руки бинты\прод. бинты с количеством не меньше 6, другой рукой разделяем стак на текущее количество бинтов в стаке и уаля, получаем пять новых халявных бинтов."
=> Перестаем дюпать бинты, увеличиваем заодно кол-во мази в стаке.

code/_helpers/text.dm, code/game/machinery/autolathe.dm, code/modules/mob/skills/skill.dm, code/modules/research/circuitprinter.dm, code/modules/research/designs.dm, code/modules/research/protolathe.dm, code/modules/research/rdconsole.dm
> _Ну что, СБ, ассистент, капитан, гп или просто левый человек в отделе разработок, не можешь сделать себе пушечку? Очень жаль._
Теперь навык комплексных устройств влияет на работу с протолатом, принтером плат и автолатом. 
ПР не несёт в себе /ухтывау/ изменений. 
- **Unskilled** - названия дизайнов нечитабельны, лист перемешивается, стоимость предметов увеличена в 2 раза, время создания увеличена на 5 тиков, 50% шанс провала при создании предмета.
- **Basic** - лист перемешивается, стоимость предметов увеличена в 1.5 раза, время создания увеличена на 3 тика, 30% шанс провала при создании предмета.
- **Trained** - стандартная работа без всяких штрафов и бонусов. 
- **Experienced** - стоимость создания уменьшена в 0.9 раз, время создания уменьшена на 1 тик. 
- **Master** - стоимость …
=> Делаем навык Complex Device полезным при работе с протолатом, принтером плат и автолатом.

code/modules/mob/living/say.dm
Убран лишний цикл с проверки резоми на шёпот
=> Убран лишний цикл с проверки резоми на шёпот

code/modules/mob/living/say.dm
Дофикшиваем слышимость шёпота у резоми
=>  Дофикшиваем слышимость шёпота у резоми

code/datums/supplypacks/munitions.dm, code/modules/research/infinity_designs.dm
В карго добавлены снаряды для орудия.
В РнД теперь доступна консоль контроля орудием.
=> БСА для РнД

code/modules/library/manuals/engineering.dm
Отредактировал текст для внутриигрового мануала по суперматерии в соответствии с текстом на вики.
=> Update in-game manual for Supermatter

code/modules/organs/internal/brain.dm
Добавил переменную с оригинального бэя, которая, возможно, фиксит баг с гибанием головы и гостания от пуль/снарядов/т.д.
=> Фикс генки(копирайт с оригинального бэя)

config/alienwhitelist.txt
=> Добавление заслуженого!

code/game/objects/items/weapons/implants/implants/imprinting.dm, code/modules/research/designs.dm
Теперь это нелегально, как для антагов, ура. С добавлением имплантада это очень важно.
=> Imprinting implant fix

code/controllers/subsystems/inactivity.dm
Òåïåðü âñå äîëæíî áûòü íîðìàëüíî.
=> Инактивность 2: Электрическое Бугалу

code/modules/power/solar.dm
Теперь выработка энергий солнечных панелей как на МКС
=> Ребаланс соляр

code/modules/modular_computers/file_system/computer_file.dm, code/modules/modular_computers/file_system/programs/antagonist/access_decrypter.dm, code/modules/modular_computers/file_system/programs/antagonist/dos.dm, code/modules/modular_computers/file_system/programs/antagonist/hacked_camera.dm, code/modules/modular_computers/file_system/programs/antagonist/revelation.dm, code/modules/modular_computers/terminal/terminal_commands.dm
* Три новые команды и одна закоменченая.
=> Terminal upgrade

code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human.dm
может будет что-то ржачноеееееееае
=> Позволяем гостоте смотреть рекордсы

code/game/objects/items/devices/radio/radio.dm, code/procs/announce.dm
перестаем слышать то, как ВЕРНЕ ПОПАЛ ПОД МЕТЕОРИТНЫЙ ШТОРМ
=> Фикс оповещания с кораблей на овермапе

test/check-paths.sh
=> Фикс Тревиса после возвращения НТСЛ

code/modules/detectivework/tools/rag.dm
Теперь есть задержка и цель необходимо грабнуть.
=> Нерф тряпочки с хлоркой

code/game/objects/items/devices/radio/electropack.dm, code/modules/modular_computers/computers/subtypes/dev_laptop.dm
Больше не нужно сто раз тыкать РОТЕЙТ ЛЭПТОП
=> Ноутбук поворачивается в сторону того кто его открыл

code/game/objects/items/weapons/tools/weldingtool.dm
=> reinclude welding sound effects

code/game/mecha/mecha.dm
=> mouse drop on mecha action

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm, code/modules/reagents/Chemistry-Recipes.dm
Да, я на полном серьезе это сделал. Славься, Элар.
1 часть арбузного сока, 1 часть топлива, 1 часть железа (из химии).
=> Коктейль "ГитХаб"

code/modules/modular_computers/terminal/terminal_commands.dm, code/unit_tests/icon_tests.dm, test/check-paths.sh
1) Элар использует << для красоты, разрешаем в тесте.
2) Элар забыл закрывающий тэг `</font>`.
3) Подключаем файл инфинити в тесты  иконок постеров (таяршип Форри).
=> Фиксы Трэвиса.

baystation12.dme
Ты не сможешь пользоваться фичами инфинимастеров, если они забудут включить их в игре. 👍
=> Подключаем аплинк-флешку.

baystation12.dme, code/modules/library/lib_items.dm, code/modules/library/manuals/engineering.dm, code/modules/library/manuals/medical.dm, code/modules/library/manuals/nanotrasen.dm
Дает возможность писать добавлять мануалам ссылки на вики, указывая ссылку полностью или только "заголовок" страницы.
=> Manual-wiki links

code/modules/power/lighting.dm
Откатывает файл, ничего не изменяет.
=> orig lighting.dm

code/modules/power/apc.dm
=> Исправление подсветки оверлея после слияния

code/datums/vote/map.dm
_Загадка была в том, что он всегда думал, что ответ всегда найдётся, но не думал, что в самый ответственный момент не услышит собственный голос._
=> Исправление воута на след. карту

maps/torch/loadout/loadout_xeno.dm
Fix #1182 *бекдуры от Архимагуся, сорян*
=> Добавление котов в вайтлист култекс. патчей

code/modules/admin/admin.dm
Обновил панель, добавил информацию о версии клиента.
=> Информация о версии бьёнда в Player Panel

infinity/code/modules/modular_computers/file_system/coding_data.dm
=> Добавление строчки о том как компилировать код батников

infinity/customs/forrya_custom.dm
-Соляр сопля соля рррярряряр
-а а а а
-у меня кастомка не спавнится
-м ну так давай ща посмотрим ну там кароче посмотри иконки, путь файлов...
*спустя пять минут*
-кароче там просто ее надо вписать потому что мы забыли
-лол
-лол
-впиши пж
-нет ты
-нет ты
-нет ты...
*спустя еще пять минут*
-ну пж блин
-нет сделай сам, там легко, ща покажу как можно сделать в два клика без гемора... 
ну теперь я надеюсь что оно будет работать но фейл смешной имхо, запилить вещь но не прописать ее....
=> ремонт моей кастомки

infinity/customs/forrya_custom.dm
=> Revert "ремонт моей кастомки"

infinity/customs/forrya_custom.dm
теперь сумку можно не только закрыть, но и открыть
также можно из нее доставать вещи, а не только класть
=> продолжаю чинить свою кастомку

infinity/code/modules/reagents/reagent_containers/food/drinks.dm
теперь надевается
раньше не надевался из за лишних строчек кода
=> починил стакан на уши

infinity/code/modules/materials/reciepes.dm
я не знаю как но я проглядел, извините
=> ремонт ремонта фичи с крафтом

code/datums/uplink/highly_visible_and_dangerous_weapons.dm
я клянусь я делаю это не ради того чтобы у людей горело
я делаю это ради того чтобы триторы, не зная что псионика вредит мозгу при слишком частом абузе, рофельно сливались от собственного жира
=> Открывает доступ к пси-импланту в аплинке.

config/alienwhitelist.txt
Выдаём вайтлист Кхармаани Wheatley
=> Вайтлист для Wheatley2013

config/alienwhitelist.txt
Выдаём вайтлист Кхаармани Dagger17
=> Вайтлист для Dagger17

config/alienwhitelist.txt
Выдаём вайтлист Кхаармани Cre77
=> Вайтлист для Cre77

infinity/code/modules/reagents/Chemistry-Recipes.dm
This PR makes possible to obtain gold and silver from solution, using frost oil. Coolant is required for gold synthesis reaction, because gold solution is obtainable from gold apples, while silver is more rare. 
Adds ability for science to complete upgrades if miner is  not available. Makes Science Hydroponics (possible source of golden apples) and Xenobio (possible source of frost oil) more useful.
=> Added silver and gold soldification from solution

code/game/machinery/recharger.dm
теперь он должен суваться в зарядку и заряжаться
=> кастомный плеер можно сразу заряжать в речаржере

config/alienwhitelist.txt
=> Обновление вайтлиста

config/alienwhitelist.txt
и кароче этот пр будут принимать еще десять дней
а потом там ошибки найдут
а потом еще что
и такие
переделывай
ааааааа
=> дайсиж - таяра

code/_macros_inf.dm, code/game/machinery/doors/airlock.dm, infinity/code/game/machinery/doors/airlocks.dm
=> Airlock ID debug browser rework

maps/sierra/sierra-1.dmm
Ошибка с энергией на складе карго.
=> Озеленяем Трэвис.

code/modules/reagents/reagent_containers/food/snacks/meat.dm
You can use any meat, just add there at least 10u of blood.
=> You can now feed slime with meat. Takes 4 meat slabs to feed slime.

config/alienwhitelist.txt
=> Seclog -resomi

config/alienwhitelist.txt
Выдаем wheatley2013 giant armoured serpentid. Он прошел тест. Теперь их слишком много. Agony!
=> Выдал wheatley2013 змейку.

config/alienwhitelist.txt
ну адхерант и адхерант че бубнить
=> выдал себе адхеранта

config/alienwhitelist.txt
=> +whitelist Adherent 5au5age

baystation12.dme, code/datums/uplink/grenades.dm, code/game/objects/items/ascent.dm, code/modules/admin/create_mob.dm, code/modules/admin/create_object.dm, code/modules/admin/create_turf.dm, code/modules/mechs/equipment/utility.dm, code/modules/projectiles/guns/launcher/grenade_launcher.dm, code/unit_tests/mob_tests.dm, html/changelogs_infinity/skonoplich-tweaks.yml, html/create_object.html, infinity/code/datums/supplypacks/medical.dm, infinity/code/game/objects/items/ascent.dm
Админокошки, ишшуи, трэвис, чейнжлог
close #1341
close #1313
close #1314
=> Мелкие правки

code/game/machinery/telecomms/telecomunications.dm, tools/dmitool/dmitool.py
У меня трэвис не подключен, так что буду следить за тестами тут
=> Правки для трэвиса на мерже

config/alienwhitelist.txt
=> +MoonMen tajaran

maps/away_inf/mining/mining.dm
Просто добавляйте эту строку к особенной машинерии.
=> Заглушка трэвису: плата реле эвэйки

code/modules/mob/living/silicon/ai/ai.dm
Думаю, описывать многое не стоит
<details>Только вот, мне кажется это костыльным способом, и можно найти что-то там глубже, но мне лень разбираться в этих кучах кода -.-</details>
=> Фикс дублирующегося ИИ

code/game/machinery/doors/blast_door.dm, code/modules/mob/living/living_defense.dm, infinity/code/game/machinery/doors/blast.dm
Привет, в этом пр были сделаны следующие изменения. Они направлены на исправления двух проблем.
* исправление и возвращение урона при закрытии створок и гермодверей.
* исправление рантайма получения урона при ударе об объект от откидывания.
=> Blast and crush

infinity/code/game/verbs/who.dm
Привет, в данном пр были сделаны изменения в функционал кнопки Who которая отображает список игроков которые на момент присутствуют на сервере. Теперь вместо вывода текста в общий чат можно открыть отдельное окошко со всей информацией, если в настройках выставлен специальный пункт.
* в предпочтениях добавлена опция с помощью которой можно сделать текст из команды Who в отдельном окне.
=> Who is Who

infinity/code/game/objects/structures/barrier.dm
Привет, немного изменений для барьеров:
* Вернул работу слоёв для барьера. Возвращён вид когда "человек стоит за барьером".
* Добавил секундное ожидание раскладки барьера и звук для предмета.
* Поправил визуальные сообщения и перенёс вызов звука после ожидания для переключения состояния.
=> Barrier things

infinity/custom_items/pmp/5au5age-Rough.json
=> 5au5age-Rough character_name fix

infinity/custom_items/general/forrya-Niyarkszherch-forrya_tajar.json, infinity/customs/forrya_custom.dm
Менее чем за ОДИН час сделано тем кто умеет в код интуитивно то, что не мог сделать весь отдел разработки за более чем ОДНУ неделю.
А все гениальное просто.
Моя кастомная сумка с добром спавнилась на полу, теперь она спавнится в клозесбеге.
Террор не мог сделать полтора нормалслота вместо одного - ему не позволял механ. Он знал что так не получится. Я смог, мне механ позволил. Жаль что я не знаю код, если бы знал что так нельзя сделать - точно бы не смог сделать это так, чтобы это работало, как сделал вот сейчас вот. Это как с ГБСами, они же тупые и не знают что летать не могут, но так как они этого не понимают - летают.
Теперь собственно плащ-клоаку можно снова вешать на плащ-куртку. Потому что иначе кринж.
В волшебную коробку теперь залазит и ПМПшка.
Давай, террор, у тебя сутки. Вроде …
=> НЕВЕРОЯТНЫЙ ПР, в котором чинятся мои кастомки.

infinity/code/modules/client/preference_setup/loadout/lists/infinity.dm
Теперь ты можешь выбрать не между тремя цветами, с привязкой к профе, а выбрать дроппоч абсолютно любого цвета. Розовый, зеленый, голубой или еще какой.
=> drop pouche, с выбором цвета (название изменено)

infinity/customs/forrya_custom.dm
Моя кастомная вуаль по моей кастомной истории.
=> Кастомная вуаль.

infinity/customs/forrya_custom.dm
Суть такова что мне казалось что я пофиксил это ранее но оно не пофиксилось?
Мы обсуждали увеличение объема подсума с одного до полутора, и я был все время уверен что оно ранее уже было пофикшено, но потом поднял локалочку и увидел что на ней-то это не пофикшено.
=> фикс моего подсумка

maps/antag_spawn/ert/ert_inf.dm, maps/sierra/sierra-1.dmm
Найдите того кто отключил телекомы на ЦК уровне и дайте люлей. Телекомы не работают из-за этого.
=> Стыковка и доступ на шаттле ОБР.

code/modules/clothing/under/jobs/security.dm
=> Починили Dermal фигню у ГСБ, теперь она будет по лучше от прямого дамага по мозгу

infinity/code/game/machinery/vending.dm
По многочисленным запросам.
А так же больше возможностей для отыгрыша и без БДСМ костюмов.
=> Контрабанда в свободный доступ, автомат актеров

code/modules/clothing/spacesuits/rig/suits/combat.dm
Понижаем характеристики военного рига чтобы сделать его более юзабельным.
=> Нерф военного рига

html/changelogs_infinity/example - копия.yml, maps/sierra/sierra-2.dmm, maps/sierra/sierra_areas.dm
Разделяем бар на уменьшенный вариант его же и кафе.
=> Разделяем бар на кафе и него же

code/game/machinery/ai_slipper.dm, infinity/code/game/machinery/security_scanner.dm
🆑 
:bugfix: Теперь у ИИ снова работают напольные мыльницы! Берегись щиткурити!
:bugfix: А щиткурити получает улучшенную версию сканеров, теперь перебрасывать предметы через него не получится.
/:cl:
=> Sexscanner

.travis.yml
=> Малый апдейт конфига Тревиса по его рекомендациям

code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
=> Фикс альтитлов професий ордер ассистенте

infinity/code/modules/clothing/head/berets.dm
берет медиков не отображался из-за того, что в дм икон_стейт берета записан не так, как записан берет в дми
теперь это исправлено, извините пожалуйста.......................(
=> фикс отображения медовского берета

infinity/customs/agrevol.dm
Убираем возможность его кастомку взять в лоадауте.
=> Revol custom fixes

code/__defines/_inf/_inf.culture.dm, infinity/code/game/objects/structures/alien/egg.dm, infinity/code/game/objects/structures/alien/node.dm, infinity/code/modules/culture_descriptor/culture/cultures_hidden_xenophage.dm, infinity/code/modules/mob/living/carbon/aliens/larva/life.dm, infinity/code/modules/organs/internal/species/xenophage.dm, infinity/code/modules/species/xenomorphs/alien_powers.dm, infinity/code/modules/species/xenomorphs/alien_species.dm, infinity/code/modules/species/xenomorphs/alien_species_handle.dm, maps/antag_spawn/abductors/abductor_equip.dm
Была исправлена огромная гора багов ксенофагов, а так же была пофикшена моментально станящая дубинка кондукторов
=> Огромный фикс абдукторов и ксенофагов, балансируя обоих

maps/sierra/job/jobs.dm
Считаю выпил у бустеров кадетов необоснованным ИС, т.к. другие ксеносы имеют ГОРАЗДО больше прав и на этом фоне данный "выпил" кажется смешным и не уместным. Я не лезу в ваши конфликты с бустерами, но не надо мне выпиливать персонажа :С
=> Возвращение бустерам кадетов

infinity/customs/diesiege.dm
Устанавливаю забытый trade_blacklist на свой капюшон.
=> DieSiegeCustomFix

baystation12.dme, code/modules/webhooks/__webhook_sanitize_inf.dm, code/modules/webhooks/_webhook.dm, infinity/code/modules/webhooks/webhook_xeno_whitelist.dm
Плюс фикс ксенопанели (ищо один)
=> Защита от дурака для вебхука

maps/antag_spawn/heist/heist_base_inf.dmm, maps/antag_spawn/heist/heist_inf.dm, maps/sierra/sierra-1.dmm, maps/sierra/sierra_shuttles.dm
Дал доступ инжам ЭК к аир алярмам и АПЦ на Хароне (но только инжам)
Плюс сделал свет на базе Хейста
=> Фиксы "стыковки" всех шаттлов 3 палубы. + доступ ЭК инжам на Хароне

code/modules/power/generator.dm, html/changelogs_infinity/vasgen40k-PR.yml, nano/templates/generator.tmpl
Небольшая фича, добавляющая повреждение термогенератора при повышенной нагрузке (3 МВт) и его последующее отключение.
=> Повреждения термогенераторов

code/datums/trading/trade.dm
Избавление от "фичи" дюпа денег через знаменитого сумасшедшего скрелла на торговцах
=> Фикс торговцев

infinity/code/modules/webhooks/webhook_roundstart.dm, infinity/code/modules/webhooks/webhook_server_start.dm
=> Раундвейтеров должно слапать не на раундстарте, а на запуске сервера

code/game/gamemodes/endgame/bluespace_jump/bluespace_jump.dm, html/changelogs_infinity/Archemagus.yml
=> Блюспейс и боты

maps/away_inf/bearcat/bearcat.dm
Ага. Всё верно. Фикс в одну строчку. Теперь небольшие изменения биркека должны нормально подгружаться.
=> Bearcat oxyfix

code/modules/mob/living/carbon/human/audible_emotes.dm
=> Фиксит крики резоми

infinity/code/modules/sprite_accessories/accessory_booster.dm
=> Фикс хвостов бустеров

infinity/custom_items/pmp/3v4ng4m1ng-Finn.json
По указаниям ГА вырезаем кастомную ПМПшку у сия хумана.
=> Убираем плеер у  3v4ng4m1ng

code/datums/supplypacks/science.dm
Добавляем возможность заказать в карго байки.
=> Байки в карго.

maps/away/meatstation/meatstation.dm, maps/away/miningstation/miningstation.dm, maps/away_inf/miningstation/miningstation.dmm, maps/sierra/sierra.dm
Принимать только после пулла #1665 - та ветка является базой для этой, потому-что фикс мерджа так и не замерджен.
Здесь ввод в ротацию двух новых авейных локаций и крупный фикс одной из них.
=> Ввод в ротацию авеек бэя

html/changelogs_infinity/terror4000rus-mate.yml, maps/away_inf/bearcat/bearcat_jobs.dm
- spellcheck: "Роль капитана на биркете переименована в первого помощника (First Mate)."
- spellcheck: "У экипажа биркета переведено описание профессий."
=> Биркет. Роль капитана становится ролью первого помощника

html/changelogs_infinity/terror4000rus-mental.yml, maps/sierra/job/jobs.dm
> Смысл роли.
> В помощи экипажу псионикой.
> Начиная от чтения мыслей.
> И заканчивая лечением тревоги волшебным прикосновением.
ИПК с псионикой - это не очень нормально. Мы не настолько фэнтези.
=> ИПК больше не может быть менталистом

code/modules/modular_computers/NTNet/NTNet_relay.dm
=> ntnetrelay return parent fix

infinity/code/modules/client/preference_setup/loadout/lists/resomi_cloaks.dm
=> Выбор цвета резомской накидки сразу в лоадауте

baystation12.dme, html/changelogs_infinity/terror4000rus-jacket.yml, infinity/code/modules/client/preference_setup/loadout/lists/suits.dm, infinity/code/modules/clothing/suits/suits.dm, maps/sierra/loadout/loadout_suit.dm
Переименованная куртка агента FSP в лодаут Сьерры. Доступна только охране.
=> Красивая куртка в охрану Сьерры

code/modules/modular_computers/file_system/programs/security/forceauthorization.dm, html/changelogs_infinity/Remindme-namefix.yml
=> Фикс имени в программе авторизации оружия

code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm, html/changelogs_infinity/terror4000rus-wchair.yml
Исправляем скорость перемещения инвалидного кресла.
=> Фикс скорости инвалидного кресла

code/modules/power/fusion/fuel_assembly/fuel_injector.dm
=> Фикс настройки инжектора раста

infinity/code/modules/clothing/suits/suits_resomi.dm
цвет капюшона не менялся, теперь норм (раньше менялся только при изменении цвета)
=> фикс накидки резоми

html/changelogs_infinity/terror4000rus - bshuttle.yml, maps/away_inf/bearcat/bearcat-2.dmm, maps/away_inf/bearcat/bearcat.dm, maps/away_inf/bearcat/bearcat_areas.dm
На биркет в левый стыковочный док добавлен функционирующий, но потрепенный шаттл с небольшим запасом топлива и ценными материалами.
=> Шаттл на биркет

code/game/objects/structures/grille.dm, code/game/objects/structures/window.dm
=> фикс страшного бага с лоуваллом

infinity/code/game/machinery/sealgen.dm
вот только сделал, а уже баги.
прикол в том что Process() по дефолту возвращает PROCESS_KILL и машинка перестает процессится
а у меня там было . = ..()
=> фикс процессинга генератора атмосферного поля

code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm, maps/sierra/datums/programs.dm, maps/sierra/job/jobs_command.dm, maps/sierra/job/jobs_security.dm, maps/sierra/sierra.dm
авторизовать варранты может: 
капитан, авд, гсб, варден, криминалисты
младшие лейтенанты и офицеры - нет :(((
=> фикс авторизации варрантов

code/game/machinery/cryopod.dm, code/modules/mob/observer/ghost/ghost.dm
Фиксим крио-трупожор.
Время до деспавна снижено до одной минуты, если вы будете гостаться находясь в крио - это, ВНЕЗАПНО ПОЛУЧИТСЯ.
+очепятка
make cryo great again
=> Фиксим крио

infinity/customs/he11d1ver.dm
Полтора месяца ожидания ради одной циферки в нике. Звучит больно.
=> Фикс кастомки Рекси

infinity/customs/fsb_set.dm
=> чуть-чуть меняем кастомку мунмена

code/modules/mob/observer/freelook/following.dm, maps/away/mining/mining_areas.dm.orig, maps/torch/loadout/loadout_storage.dm
Кто-то вмержил ПР прямо с неразрешёнными конфликтами. Как? А хуй его знает
UPD: два ПРа, специально проверял
=> Чиним лажу

code/modules/client/client_procs.dm, code/modules/mob/new_player/login.dm, html/changelogs_infinity/fullscreen.yml, infinity/code/modules/client/client_procs.dm
Лень писать чейнжлог, суть - автоматический подгон фулскрина теперь должен работать при заходе на сервер.
=> Фикс фулскрина

baystation12.dme, code/datums/supplypacks/engineering.dm, html/changelogs_infinity/DonaldoTHT-PR-1774.yml, infinity/code/datums/supplypacks/engineering.dm
resolve #1679 
Теперь реле теллекомов можно будет достать в карго, без щитспавна за каких-то 45 кредитов(Если цена не устраивает, можем поднять). Всё
=> Реле Теллекомов отныне будет доступно для заказа в карго

maps/away_inf/patrol/patrol.dmm
resolve https://discordapp.com/channels/194724102496321537/505387976680013824/781078512521052230
Почитайте #reports, почитайте название, мне лень что-то умное писать
Высасывающие атмос части патрульника были заменены на укреплённую плитку
=> Патрульник более не должен высасывать атмосферу экзопланет

code/_helpers/text.dm, code/modules/codex/entries/paperwork.dm, code/modules/paperwork/carbonpaper.dm, code/modules/paperwork/paper.dm, code/modules/paperwork/photocopier.dm
Устраняет пару эксплойтов, на этом всё.
=> Удаление тега [img] и фикс многократных декодов в бумаге

code/game/objects/items/devices/radio/encryptionkey.dm, html/changelogs_infinity/DonaldoTHT-PR-#1785.yml
В наушник РД была добавлена экспедиционная частота, потому-что он отвечает и за него тоже.
=> Экспедиционную частоту в наушник РД

code/modules/mob/observer/freelook/eye.dm, html/changelogs_infinity/smartkar-blob.yml, infinity/code/modules/blob/abilities.dm, infinity/code/modules/blob/blob.dm, infinity/code/modules/blob/blobbernaut.dm, infinity/code/modules/blob/eye.dm, infinity/code/modules/blob/spore.dm, infinity/code/modules/blob/strains.dm
=> Фикс блоба

html/changelogs_infinity/DonaldoTHT-PR-#1781.yml, maps/away_inf/liberia/liberia_areas.dm
Челнок торговцев "Мул" отныне защищает Вас от радиации, прямо как и любой другой порядочный челнок
=> Добавляем заshitу от радиации на Мул

baystation12.dme, code/modules/client/preference_setup/global/preferences.dm, code/modules/mob/living/say.dm, infinity/code/modules/mob/floating_message.dm
Портировано с Небулы. Открыто для diff'а и теста.
=> Chat Bubbles

infinity/code/game/objects/structures/holoplants.dm
Гологоршок теперь можно выключить альт-кликом
=> Holoplants feature

baystation12.dme, code/modules/client/preference_setup/global/preferences.dm, code/modules/mob/living/say.dm, infinity/code/modules/mob/floating_message.dm
:cl:
rscadd: Всплывающие реплики над игроками
/:cl:
=> Chat Bubbles (#1663)

code/modules/clothing/spacesuits/rig/suits/combat.dm, code/modules/clothing/spacesuits/rig/suits/ert.dm, code/modules/clothing/spacesuits/rig/suits/station.dm
Теперь ИПЦ могут носить большинство стандартных ригов.
=> [BUGFIX] ИПЦ и РИГи

code/modules/species/station/human_subspecies.dm
:cl:
refactor: Откатываем нерф триторианцев до беевских значений
/:cl:
=> Откатываем нерф триторианцев

baystation12.dme, infinity/code/modules/shield_generator/shield_genrator.dm
:cl:
imageadd: Генераторы щита могут красить свои щиты.
/:cl:
=> Менять цветы щитов

maps/sierra/sierra_security_state.dm
Переведены названия кодов угроз. Теперь они должны отображаться на русском языке
=> переводим названия кодов

code/datums/uplink/services.dm
Фиксит трейторский взломщик аннонсов цент-кома. Аплинк-Слейвы снова могут делать РПи
=> Фикс аннонсмента ЦК для Fucking slaves синдиката.

infinity/code/modules/reagents/reagents_containers/food/drinks/bottle.dm
Специальная волшебная бутылочка для ивентов.
=> Банка с триглазом для ивентов

code/modules/projectiles/guns/energy/vox.dm, code/modules/projectiles/projectile/energy.dm
This reverts commit aceb0d54c28632da72ac251dc5db1617b504ac52.
:cl:
balance: Откатили нерф флюкса
/:cl:
=> Revert "Изменяем flux у воксов."

code/modules/admin/DB ban/functions.dm, code/modules/admin/NewBan.dm, code/modules/admin/topic.dm, infinity/code/modules/admin/ban_messages.dm, infinity/code/modules/webhooks/webhook_ban_message.dm
:cl:
spellcheck: Теперь уведомления о банах работают лучше
/:cl:
=> Улучшаем уведомления связанные с банами

maps/sierra/job/outfits.dm
Адхеранты и жуки на бармене страдали без кассеты, теперь будут страдать люди без сумок.
:cl:
bugfix: Теперь кассета будет спавниться у барменов адхерантов и ГБС
/:cl:
=> Фикс спавна кассеты

maps/sierra/job/outfits.dm
Почему-то переменная не работала без list срочно принять!!!!
=> Фикс фикса кассет

maps/away/ascent/ascent.dm, maps/away/bearcat/bearcat.dm, maps/away/skrellscoutship/skrellscoutship.dm, maps/away_inf/bearcat/bearcat.dm, maps/away_inf/liberia/liberia.dm, maps/away_inf/sentinel/sentinel.dm
Почти все населенные авейки получили почти оригинальную стоимость с бэя. За исключением биркета, что сделан дешевле. Либерия получила стоимость ноль, так как она и так спавнится с стопроцентным шансом и смысла ей занимать место в cost нет, правда я не уверен будет ли это нормально работать.
Вокзобазу я не трогал, потому что всё ещё надеюсь на её выпил.
Одобрено лично Никрозом. 
:cl:
balance: Изменена стоимость населенных авеек в сторону уменьшения. 
/:cl:
=> Пробный баланс населенных авейкарт

baystation12.dme, infinity/code/datums/uplink/devices and tools.dm, infinity/code/game/objects/items/devices/constrictor_harness.dm, infinity/code/game/objects/items/weapons/storage/uplink_kits.dm
**Описание:**
Итак, теперь в аплинке, в разделе "Гаджеты и Инструменты", у нас появился "Сжимающий корсет" ака "constrictor harness". Основная его задача - сжимать грудную клетку Вашего персонажа так сильно, чтобы она могла втиснуться в вентиляционную шахту. Теперь подобно главному герою Вульфенштайна Вы можете обходить стороной большинство угроз и преград, залезая в вентиляцию. В комплект входит небольшой баллон и маска для трубного дайвинга.
**Однако!**
* Вам стоит учесть, что находясь в трубе персонажу нужно дышать и находиться в комфортной среде. Это означает, что придётся избегать ползанья в красных трубах, поскольку там низкое давление и множество непригодных для дыхания газов. Синий трубы станут самым комфортным для Вас средством передвижения, поскольку в них находится кислород и …
=> Сжимающий корсет, или гаджет, позволяющий залезать в вентиляцию

maps/away/ascent/ascent.dm, maps/away/bearcat/bearcat.dm, maps/away/skrellscoutship/skrellscoutship.dm, maps/away_inf/bearcat/bearcat.dm, maps/away_inf/liberia/liberia.dm, maps/away_inf/sentinel/sentinel.dm
Пробный период пройден. Пробуем обратный вариант обратно и смотрим динамику
=> Revert "Пробный баланс населенных авейкарт"

maps/away/ascent/ascent.dm, maps/away/bearcat/bearcat.dm, maps/away/casino/casino.dm, maps/away/errant_pisces/errant_pisces.dm, maps/away/magshield/magshield.dm, maps/away/meatstation/meatstation.dm, maps/away/miningstation/miningstation.dm, maps/away/skrellscoutship/skrellscoutship.dm, maps/away/slavers/slavers_base.dm, maps/away/voxship/voxship.dm, maps/away_inf/bearcat/bearcat.dm, maps/away_inf/blueriver/blueriver.dm, maps/away_inf/liberia/liberia.dm, maps/away_inf/mining/mining.dm, maps/away_inf/sentinel/sentinel.dm, maps/away_inf/smugglers/smugglers.dm, maps/away_inf/yacht/yacht.dm
Новая система стоимости, теперь всё неиграбельные авейки стоит 1 очки, играбельные 0.5, но имеют низкий приоритет спавна. На практике в предварительном и в теории это должно привести к спавну всего двух авейкарт с людьми.
:cl:
balance: Снова новый баланс авейкарт. Теперь должно быть ровно две.
/:cl:
=> Test away cost part two.one

infinity/customs/mixanovr64.dm
Переключение - есть
Урон - есть
Звук - есть
Складывание - есть
Не кладётся в ножны - есть
=> Перепиливаем кастомку Михи

infinity/code/modules/client/interface_mode.dm
:cl:
tweak: Переработан код для изменения темы интерфейса.
/:cl:
=> Рефактор тем интерфейса

code/datums/supplypacks/machinery.dm, code/game/machinery/kitchen/microwave.dm
Я считаю, что это настоящий трындец.
Выполняется вот этот Репорт
:cl:
bugfix: Исправлена проблема с микроволновкой, которую привозили каргошаттлом. Теперь в ней будут появляться необходимые для работы комплектующие.
/:cl:
=> Лахеш превратился в фиксика и залез в микроволновку чтобы её починить ужас

infinity/customs/taushai.dm
=> Кастомка Таушая: небольшие корректировки по просьбе заказчика

infinity/custom_items/pmp/5au5age-Rough.json
Ну в принципе да, игрок меня попросил, я сделал для своего солнышка ding-ding <3
=> Перенос кастомки 5au5age  на другое имя

maps/sierra/loadout/loadout_accessories.dm
По просьбе Таушая и работяг из "других" систем.
:cl:
rscadd: В лодауте теперь можно взять "просто паспорт" от Сола или ГКК.
/:cl:
=> Даём возможность игрокам выбирать просто паспорта Сола или ГКК

code/modules/clothing/spacesuits/rig/rig.dm
Closes #1931
:cl:
bugfix: Фикс рантайма не дававшего разложить обычные РИГи.
/:cl:
=> Фикс ригов

maps/sierra/job/jobs.dm
🐛 Жуководы ждут проф, а я жду на вики информацию об их размножении и спаривании с другими видами ага 🐛
:cl:
balance: Рабочие должности перераспределены опять.  На этот раз мы вернулись к тому, что было изначально, но c одной правкой: минусовые грейды потеряли такие социальные профы, как Бармен и Повар.
=> Работа для 🐛 

infinity/custom_items/general/elloncake-Xri-voidsuit.json
а я гей и пробую починить кастомку
=> Эллонкейк победил

baystation12.dme, infinity/code/game/objects/items/donate/costume_bags.dm, maps/sierra/loadout/loadout.dm
=> Штучки для падпещеков патреона

maps/bearcat_inf/bearcat-2.dmm, maps/bearcat_inf/bearcat-3.dmm
поправил трубы у автошатеров и перенс шлюзы с опенспейса на турф
=> bearcat_inf fix

maps/bearcat_inf/bearcat-2.dmm, maps/bearcat_inf/bearcat-3.dmm, maps/bearcat_inf/bearcat_inf.dm, maps/sierra/items/items.dm, maps/sierra/loadout/loadout_accessories.dm, maps/sierra/sierra-1.dmm, maps/sierra/sierra-2.dmm, maps/sierra/sierra-3.dmm, maps/sierra/sierra.dm
Сейчас проверим как можно сделать
=> Bearcat_fix

code/game/objects/items/weapons/grenades/prank_grenades.dm, code/modules/mob/living/simple_animal/hostile/hivebot.dm, code/modules/spells/aoe_turf/conjure/druidic_spells.dm, code/modules/spells/aoe_turf/summons.dm, infinity/code/modules/mob/living/simple_animal/aquatic/sharks.dm, infinity/code/modules/mob/living/simple_animal/friendly/snake.dm, infinity/code/modules/mob/living/simple_animal/hostile/changeling_mob.dm, maps/away_inf/blueriver/blueriver_mob.dm
Забыл описание, ага
Бей переделал немного механ симпов, поэтому нам нужно некоторых мобов подогнать под новый механ.
Культ Смарткара не трогался
=> Натуральное оружие для натуральных мобов

infinity/custom_items/general/deksters-Dexter_Steinhardt-Caelestium_rig.json
Перчатки больше не шлем, ботинки больше не шлем, нагрудник больше не шлем
=> Fix of names for Dexter customka

code/game/area/areas.dm, infinity/code/game/machinery/lightswich.dm, infinity/code/game/machinery/security_scanner.dm
:cl:
rscadd: Уходя гасите свет
tweak: По ПКМ на выключателе света можно менять режимы автоматики
/:cl:
=> Экономьте свет, дятлы

maps/away/ascent_caulship/ascent_jobs.dm
Возвращаю бейский вариант, который по какой-то причине был заменен на нашу старую версию с сидшипа.
=> Нормальное описание

infinity/custom_items/general/adro244-Irin-TT-Suit.json
=> Фикс путя к кастомке

maps/sierra/datums/reports/command.dm, maps/sierra/datums/reports/iaa.dm
:cl:
bugfix: Правим грамматику, меняем доступ к бумажкам командования.
/:cl:
=> мелкофиксы бумажек

code/modules/blob/blob.dm
А почему люди должны видеть сладкие места через зеленую биомассу
:cl:
balance: Блоб непрозрачен как на бэе
/:cl:
=> Блоб теперь непрозрачен

sql/migrate/V006__InfinityTables.sql
=> Исправление: добавить недостающую SQL схему в БД 

code/_onclick/hud/skybox.dm, code/controllers/subsystems/skybox.dm
🆑 Vallat
bugfix: починили космос (привет из SS220 Paradise)
/🆑
=> Ремонт скайбокса

infinity/code/modules/telesci/telepads.dm, infinity/code/modules/telesci/telesci_computer.dm
:cl:
balance: Теперь телесало учитывает наличие овермапы и огромных растояний. Готовьте свою смекалку.
/:cl:
=> Чиним работу телесала

baystation12.dme, code/_helpers/global_access.dm, code/_helpers/icons.dm, code/modules/admin/map_capture.dm, infinity/code/game/objects/item_mob_overlay.dm, test/check-paths.sh, test/run-test.sh
=> getIcon с Небулы

html/changelogs_infinity/fix-skybox.yml
Дополняем чейндж-лог о починке скайбокса.
Конец пр-а.
=> Дополняем чейндж-лог сообщением о починке скайбокса

infinity/code/modules/mob/holder.dm, infinity/code/modules/reagents/reagent_containers/food/snacks.dm, maps/sierra/machinery/vendors.dm
Патреоно-бояре могут выдохнуть - петкуб с ящерками снова в рабочем состоянии и ящерки снова будут греться от Ваших тёплых сердец. (Возможно, что ещё их снова можно брать в ручки, но это не точно)
Аккумуляторы теперь нормально выдаются в вендомате робототехников
:cl:
bugfix: РНД: аккумуляторы снова нормально выдаются из вендомата робототехников.
bugfix: Лодаут: Пет-куб с ящерками вновь спавнит ящерок.
/:cl:
=> Испрвляем петкубы с ящерками и выдачу аккумуляторов из вендора рнд

infinity/custom_items/general/Filiae-ea-high-qual-beret.json
Перенос кастомки одобрен Никрозом
(вау офигеть ГитХаб Декстоп такой удобный)
=> Таскаем туда-сюда кастомки

code/game/objects/structures/crates_lockers/closets/__closet.dm
Теперь кнопки над цифрами, а цифры между кнопок.
Кнопка "проверить замок" сместилась вниз и теперь имеет более точный тайтл.
Перед мержем стоит проверить ингейм, позже это сделаю, если никто не поможет с этим или если Тревис не скомпилит
:cl:
tweak: Интерфейс взлома шкафчиков мультиметром переработан и теперь кнопки подбора цифр находятся в ровном столбце с цифрами.
/:cl:
=> [WIP] Нормальный интерфейс подбора кода мультиметром

infinity/customs/he11d1ver.dm
-Перчатки нужны?
-Нет.
....
-А где перчатки?
=> Кастомка Рекса

infinity/custom_items/general/he11d1ver-Aard-meshok.json
=> Все еще кастомка Рекса

infinity/custom_items/general/Foltynis.-meshok-Angel.json, infinity/custom_items/general/MrNicolas-meshok-Valera.json, infinity/customs/he11d1ver.dm
Кастомки Николаса и Фолтиниса.
=> Еще два кастомки.

infinity/custom_items/general/Foltynis.-meshok-Angel.json, infinity/custom_items/general/MrNicolas-meshok-Valera.json, infinity/custom_items/general/he11d1ver-Aard-meshok.json, infinity/custom_items/general/thehero13-Alex-meshok.json, infinity/custom_items/general/wolforbykot-kegan-suit.json
Ограничения для кастомок: Вульфора, Рекса, Николоса, Героя и Фолтица.
=> Ограничения

code/modules/crafting/crafting_floorbot.dm
Я щитаю, что сменить требование в крафте с 10 плиток на 1 - это хорошее решение проблемы)00)
=> Чиним флурбота методом костылей. Again

infinity/code/modules/clothing/under/under.dm, maps/sierra/loadout/loadout_shoes.dm, maps/sierra/loadout/loadout_uniform.dm
Данный пул-реквест направлен на добавление в лодаут двух вещей - рубашки без аксессуаров (галстуки и пиджачки) и туфли, которым можно поменять цвет.
* Изменено описание у рубашек
* Добавлена возможность взять рубашку без галстука и пиджака
* Добавлена возможность взять в лодауте туфли с настраиваемыми цветами
:cl:
rscadd: Лодаут: добавлены рубашки без аксессуаров.
rscadd: Лодаут: добавлены туфли, которым можно поменять цвет.
tweak: Изменено описание у рубашек.
/:cl:
=> Добавляем рубашки и цветные туфли в лодаут

maps/sierra/items/encryption_keys.dm, maps/sierra/items/headsets.dm, maps/sierra/job/outfits.dm
:cl:
tweak: Наушник РД и его ключ переименованы из chief science officer's headset в research director's headset.
rscadd: ЛЭК: В ключ наушника добавлена частота научного отдела.
rscdel: Пилот: Из ключа наушника пилота убрана частота отдела поставок.
bugfix: Пилот: исправлена выдача наушника при заходе в игру. Теперь будет выдаваться именно наушник пилота, а не исследователя.
/:cl:
=> Вы знаете, я своего рода Директор Исследований.

maps/sierra/job/jobs_command.dm
Упс, я чуть-чуть забыл подправить три буковки в моём ПР про перевод...
=> маленькая заплатка

code/datums/uplink/ammunition.dm, code/datums/uplink/highly_visible_and_dangerous_weapons.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/mob_helpers.dm, code/modules/projectiles/projectile/beams.dm, code/modules/projectiles/projectile/bullets.dm, code/modules/projectiles/projectile/energy.dm, code/modules/projectiles/projectile/magnetic.dm
Ну все параметры прожектайлов возвращены к оригинальным значениям бэя. Больше никаких смешных ваншотов, бесполезных пушек и дизбаланса.
:cl:
balance: Бэевский баланс прожектайлов был возвращен
/:cl:
=> Больше никакого криворукого баланса

maps/sierra/datums/reports/command.dm
:cl:
bugfix: Исправляем проблему с исчезнувшим корпоративным запросом у глав.
/:cl:
=> Окей, я слепой.

infinity/code/game/machinery/security_scanner.dm
:cl:
fix: исправлено логическое выражение для проверки цели(моба) на наличие контрабанды
:cl:
=> Fix: исправлена работа турникетов службы безопасности

infinity/code/game/machinery/security_scanner.dm
:cl:
fix: улучшен код сканера безопасности для покрытия всех случаев а так же проведена его оптимизация
:cl:
=> Fix: улучшен код сканнера безопасности

infinity/code/game/machinery/security_scanner.dm
:cl:
fix: испралвен баг, когда переменная которая хранила список вещей человека, ссылалась на эток список, модифицирововав его, то есть вырезая органы, и удаляя вещи
:cl:
=> Fix: исправления бага со списком в сканере безопасности

infinity/customs/unchi_turtleneck.dm
Просто изменение описания моей кастомки, ничего больше.
=> Изменение описания кастомки

infinity/code/game/machinery/security_scanner.dm
:cl:
tweak: изменены необходимые доступы для ношения оружия при проходе через турникет
:cl:
=> Fix: изменены необходимые доступы для турникетов

code/modules/species/outsider/zombie.dm
Изменение заключается в том, что теперь карта, шлем, маска, очки с зомбей не будут пропадать. В идеале добавить возможность открывать двери, но сейчас как-то лень. 
:cl:
experiment: При перерождении в качестве зомби, персонаж не будет терять свои вещи.
/:cl:
=> Небольшой бафф/ребаланс зомбей

code/datums/uplink/ammunition.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/mob_helpers.dm, code/modules/projectiles/projectile/beams.dm, code/modules/projectiles/projectile/bullets.dm, code/modules/projectiles/projectile/energy.dm, code/modules/projectiles/projectile/magnetic.dm
=> Revert "Больше никакого криворукого баланса"

maps/sierra/job/jobs_research.dm
Какой-то гений когда-то дал СНС возможность брать мастера химии, место мастера анатомии. Как его версия на Факеле или РД. И сейчас выходит так, что РД имеет доступ к мастеру анатомии, а СНС к мастеру химии. Почему и зачем - непонятно. Фиксим.
=> Фикс говна СНС

code/modules/mob/living/silicon/robot/drone/drone.dm
:cl:
balance: Дроны теперь стали намного быстрее...
/:cl:
=> Теперь дроны стали быстрее

infinity/customs/he11d1ver.dm
=> Фиксим кастомку

infinity/custom_items/general/unchi-Agneshka-guitar.json
Переношу кастомку с перса на перса и немного меняю описание оной, ничего более.
=> Перенос кастомки

code/modules/client/preference_setup/loadout/lists/utility.dm, maps/sierra/loadout/loadout_accessories.dm
:cl:
rscadd: В лодаут была добавлен фонарик-ручка. Его могут взять врачи, учёные, а также полевой медик.
/:cl:
=> Добавление фонарика-ручки в лодаут.

infinity/customs/forrya.dm, infinity/customs/hodovoy.dm
Фикс кастомок Форри и Ходового
=> Фикс кастомок

code/modules/modular_computers/file_system/programs/generic/reports.dm
Чиним спрайт у консолей с программой репортов.
=> Фиксим программу репортов.

infinity/customs/kilka.dm
Я добавил в свою кастомку сумку, да, я получил разрешение как от вольфора, так и от Никроза.
И я до ужаса обожаю сосать члены, не могу перед ними устоять
Как же я хочу, чтобы меня алкаши изнасиловали
=> Я обожаю члены

infinity/custom_items/general/nicroz-gun.json
:cl:
rscadd: Выдаём никрозу винтовку которая может уничтожать лица, в принципе как все винтовки
/:cl:
=> кастомка для НЯкроза

code/modules/clothing/head/misc.dm, infinity/code/modules/clothing/head/head.dm
:cl:
bugfix: Хиджаб скрывает флавор головы
/:cl:
PS. я ОЧЕНЬ надеюсь что это ПОСЛЕДНЯЯ ПРка
close #1552
=> Хиджаб, надеюсь финальное

maps/sierra/datums/reports/medical.dm
:cl:
rscadd: Добавлены справки об оказании мед. услуг в Report Editor.
/:cl:
=> Бумажки, бумажки. Больше.

maps/sierra/items/items.dm
:cl:
rscadd: Были добавлены паспорта для Калдарка, Бринкбёрна, Мирании и Авалона. 
/:cl:
=> Добавление паспортов.

code/game/objects/structures/railing.dm, infinity/custom_items/general/nicroz-gun.json
Даём Никрозу лицензию на пушку
плюс дефикс перилов, теперь вы можете снова лазить в стены
________________
Удаляем мораль у меня
=> Лицензия для пушки Някроза

infinity/code/modules/emotes/definitions/audible.dm
:cl:
soundadd: Добавлены целых две вариации смеха для кукол мужского и женского пола.
/:cl:
fix #2163
=> больше смеха

baystation12.dme, maps/sierra/areas/sierra1.dm, maps/sierra/sierra-1.dmm
*Изменена подача тока на Петров. Теперь она идёт не через стену, а через шлюз.
*Перестройка карго. Укорочена конвеерная линия, вытащили мусорные трубы из стен.
*Добавлено новое помещение для сычей-работяг(грузчиков).
*Добавлено большое количество огнетушителей в ангар за место мятных пряников для тушения пожаров.
:cl:
maptweak: Карго перестреоно.
maptweak: Добавлена новая комната для грузчиков.
maptweak: Изменен провод подачи тока на Петров.
maptweak: Добавлены огнетушители в ангар.
/:cl:
P.S Зафиксил код. Проверил в компиляторе. Проверил в игре. Всё работает
=> МКП v.2: Кишиневский фикс

code/datums/shackle_law_sets.dm
А то шо у нас половина переведена а половина нет... Проверено, работает.
=> 99 процентный перевод законов

maps/away_inf/yacht/yacht.dmm
* Созвав консилиум судостроительных компаний и инженеров, было принято пересмотреть некоторые моменты на яхте.
_Было решено пересмотреть технику безопасности, **добавив поручни около солнечных панелей и предупредительные линии со знаками**! Мы заботимся об безопасности наших клиентов!_
_Жалобы наемных поваров на то, что нет нагревателей и охладителей были услышаны! Мы решили эту проблему, **удлинив немного кухню и добавив их**!_
_**Библиотека-кабинет стала чуть больше и обзавелась цветочком**, чтобы радовать глаз любого книжного червя, подолгу читающего книжки. Иногда, нужно размяться и проветриться, поглядев на зеленое чудо!_
_Консилиум был обеспокоен всего одним мусорным юнитом... Теперь добавлено три новых! 2 в машинный отсек по разные стороны, чтоб не бегать как обезьяна с гранатой, …
=> Чудо-яхта v2.1! Мелкий апдейт

maps/sierra/areas/sierra3.dm, maps/sierra/sierra-3.dmm
Вся информация в предыдущем ПРе
EDIT:
**-Вы продоете главперсоналовое?
-Нет, только показываю.
-Красивое...**
* Новый, более логичный и грамотно собранный нашими лучшими ~~тюремными~~ архитекторами офис главы персонала. Вход отныне находится не с личной каюты, а с офиса.
* Робастная персональная каюта с видом на КПЗ. Насладитесь минутами спокойствия, наблюдая за колизейными поединками между арестантами и охраной! (Защитные створки на случай победы зеков прилагаются)
* Новый, уникальный для ролевого проекта Инфинити RU бренд - Unused Office! По техническим причинам был расположен на месте бывшей каюты Главы Персонала.
* Оптимизировано пространство телекоммуникаций, перенесено хранилище комплектующих. Модифицированы технические помещения телекоммуникаций.
:cl:
maptweak: Офис Главы Персонала …
=> Новый Офис ГП, попытка вторая

infinity/code/modules/mob/living/silicon/robot/flying/module_flying_emergency.dm, infinity/code/modules/mob/living/silicon/robot/modules/module_medical.dm, infinity/code/modules/mob/living/silicon/robot/modules/module_miner.dm
УБираем повторные проки, которые я пропустил.
=> Убираем повторные проки

maps/away_inf/yacht/yacht.dmm
коробки в складском, кальян на барной стойке 
:cl:
maptweak: Кальян добавлен раундстартом на яхту. Ура?
/:cl:
#2332
=> Кальян на яхту

code/modules/client/preference_setup/background/02_language.dm, maps/sierra/job/jobs_command.dm, maps/sierra/machinery/doors.dm, maps/sierra/sierra-1.dmm, maps/sierra/sierra-2.dmm, maps/sierra/sierra-3.dmm
В этом пулл-реквесте совсем чуть-чуть изменяется карта.
* Офис менталиста переделан. Теперь он меньше похож на подсобку уборщика, лучше освещён и вообще интерьер больше похож на место для восстановления рассудка, чем на комнату для пыток. Да и шторка позволяет уединиться у пси-метра.
<p align="center">
</p>
* Джереми Мак-Тензи в очередной раз перепил алкоголя и устроил набег на мозги Стоуна, прожужжав ему как плохо быть Главой Персонала, иметь полный доступ к Бригу, но не иметь доступ к Вардену. Что же, теперь у Главы Персонала есть недостающий доступ Вардена.
* Джереми этого оказалось мало, поэтому он, опираясь на свои гендерно-полит-философско-индивидуальные координаты сказал "Все главы будут экономически равны".  На данный момент вступает в силу эксперимент, связанны с экономической …
=> Doors map commands

code/game/objects/items/paintkit.dm
Обычный пулл-реквест с фиксом кастомки эллонкейка.
=> Fix Elloncake custom voidsuit sprite

code/game/world.dm
**НЕ МЕРЖИТЬ!** Не могу сказать, что данный вариант правильный для вашего кода, тем не менее это работает. Если есть живые мейнтейнеры, то лучше сделайте возможность конфигурировать эту строчку на случай конфликтов с даунстримами.
* Первая часть интеграции с SS13.SU.
* Прямое изменение статуса без возможности отредактировать в конфигурационном файле. 
:cl:
experiment: Добавление домена SS13.SU в статус сервера.
/:cl:
=> Integration v1

infinity/code/game/objects/structures/crates_lockers/closets/secure/medical.dm, maps/sierra/areas/sierra3.dm, maps/sierra/sierra-2.dmm, maps/sierra/sierra-3.dmm, maps/sierra/sierra_areas.dm
Каждый хороший ГР стабильно делает следующее:
1. Шлёт игроков нахер
2. Добавляет в билд спорные предметы
3. Перепиливает какой-нибудь отдел просто ПОТОМУ ЧТО
Я, как видите, сделал кое-что из этого пункта. В этом пулл-реквесте перерабатывается медбей. Белый храм трапусек и пушистых животных-хирургов. Понравится ли это вам, игрокам - вопрос очень хороший.
В этом разделе я постараюсь расписать каждое изменение со своими комментариями.
Как мы знаем, Сьерровский медебей - это медбей Факела. Поэтому я бы сказал, что мы заставили Сьерровского торча словить приход и преобразоваться. Скорее-всего это напомнит игрокам медбей до его последней перестройки Эларом.
Как видите, между кабинетами и другими помещениями есть звено - коридор. Считайте его одним едином хабом нового медбея. Такая планировка …
=> Rebuild medical bay on map

maps/sierra/sierra-3.dmm
Ура, финансирование R&D увеличено.
* Общий склад R&D: количество стали изменено на +30
* Общий склад R&D: количество стекла изменено на +30
* Общий склад R&D: количество пластали изменено на +20
* Отдел разработки R&D: добавлен раздатчик кислоты
* Отдел робототехники R&D: количество стали изменено на +15
* Отдел робототехники R&D: количество пластали изменено на +40
* Отдел робототехники R&D: добавлен раздатчик кислоты
:cl:
maptweak: Общий склад R&D: количество стали изменено на +30
maptweak: Общий склад R&D: количество стекла изменено на +30
maptweak: Общий склад R&D: количество пластали изменено на +20
maptweak: Отдел разработки R&D: добавлен раздатчик кислоты
maptweak: Отдел робототехники R&D: количество стали изменено на +15
maptweak: Отдел робототехники R&D: количество пластали …
=> Add some resources to RND
