infinitystation/Baystation12

code/modules/mob/living/autohiss.dm

autohiss_extra для ящеров локализован как (ч= "щ" "щщ" "щщщ") вместо (х= "ks" "kss" "ksss")

Auto-Hiss на русском для ящеров и таяр.

---

code/modules/mining/mine_turfs.dm
code/modules/mining/ore.dm
code/modules/mob/inventory.dm
code/modules/mob/living/carbon/human/inventory.dm

- Портирование функции автоматического подбора руды с репозитория ParadiseSS13 (ссылка на оригинальный запрос слияния https://github.com/ParadiseSS13/Paradise/pull/3680)
- Если во время пересечении тайла с находящимися на нём рудами носить в руках/на поясе шахтёрскую сумку для руд, вся руда будет автоматически перемещаться в сумку.
- Небольшое обновление стиля строения кода для функций `New()` и `proc/update_ore()` рудной сумки.
- Добавлены проверочные функции `get_all_slots` для ветки `/mob/`, is_in_hands для ветки `/mob/living/carbon/human/`.

Портирование функции автоматического подбора руды с Paradise

---

code/__defines/chemistry.dm
code/__defines/misc.dm
code/modules/mob/living/carbon/human/life.dm

- [Port] Теперь голодание это нечто более чем индикатор и сильное недоедание вызывает слабость или даже медленная смерть.

starving to death

---

code/game/gamemodes/objective.dm

Теперь мультиметр не может быть целью для ролей.

Убираем мультиметр из возможных целей ролей.

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

Добавил агрессивным мобам возможность ломать: низкие стенки (те, что под окнами), баррикады (деревянные и переносные), барьеры, надувные стенки, строящиеся и целые двери, поручни, ленты, гирдеры стен. Это сделает их чуть более опасными, так как теперь они могут проламываться в комнаты даже если там стоят разного вида баррикады и окна.

Улучшение агрессивных мобов

---

code/game/machinery/doors/door.dm
code/game/objects/structures/barrier.dm
code/modules/emotes/definitions/audible.dm
code/modules/mob/living/carbon/human/update_icons.dm

Что нового:
* Изменена проверка в иконках, барьерах, дверях и эмоутах. Теперь она осуществляется по имени расы, а не по химическому тегу

Изменение способа проверки расы для резоми и ксеноморфов

---

code/game/objects/items/devices/radio/radio.dm

Что нового:
* В связи с особенностью механики и истинном предназначении переменной `on` было решено заменить её на broadcasting = 0. Это должно исправить проблему с открытием интерфейса (#451)

Исправление мгновенного закрытия интерфейса радио

---

code/game/machinery/doors/airlock.dm

Что нового:
* Теперь шлюзы вне зависимости от степени защищённости платы (secured_wires) будут отзываться и пищать при отказе в доступе. Плюс, при взломе с помощью емаг-секвенсора будет сопровождаться аналогичный звук

Шлюз будет пищать при отказе в доступе даже если недостаточно защищён

---

code/modules/spells/aoe_turf/blink.dm

Что нового:
* В целях баланса маг снова может использовать заклинание Blink если закован или оглушён
* Радиус действия Blink'а изменён с 7 до 14
* Размер дымовой завесы увеличен
* Убрана дымовая завеса на месте назначения

[READY] Разнёрф телепортационных заклинаний мага

---

code/datums/communication/looc.dm
code/modules/mob/mob_helpers.dm
code/modules/mob/observer/ghost/ghost.dm

Что нового:
* LOOC уважает настройки анонимности: Если не в игре - отображает имя призрака.
* Появление не отображается в чат при включённой анонимности.
* Переработана кнопка скрытия собственного спрайта.

Изменения для призраков

---

code/game/machinery/doors/firedoor.dm
maps/torchinf/job/torch_jobs.dm
maps/torchinf/torch_define.dm
maps/torchinf/torch_ranks.dm

:cl:
tweak: Резоми и Таяры могут в ЭК.
tweak: Резоми на могут в корпоративную охрану, каптенармусов, корпоративных представителей и РД.
/:cl:
Что по мелочам, так здесь уменьшение количества спавнящихся на овермапе объектов (для повышения производительности) и фикс спрайта противопожарных створок на торче.

Резоми и Таяры в ЭК + мелочи

---

code/game/verbs/who.dm

Изменение верба **who** для простых игроков.  Теперь же игроки могут посмотреть, какой ckey **играет/наблюдает/находится в лобби**. 
**Умершие/загоставшиеся** игроки засчитываются как играющие, тем самым не показывая что они "всё".
С оформлением у дела плохи, поэтому я не знаю, сойдёт ли такое или нет.

Улучшение верба who

---

code/controllers/subsystems/inactivity.dm

Теперь, если в конфиге заккоментирован KICK_INACTIVE или равен нулю, кик отключается, а не кикает за АФК в 0 минут.

Опциональное отключение кика при АФК

---

code/modules/projectiles/guns/energy/secure.dm
code/modules/projectiles/secure.dm

1)Теперь secured пушки требуют регистрации.
2)Зарегистрировать их можно только картами с доступом в бриг или на мостик.
3)Использовать их после регистрации может кто угодно, проверки на карту нет.

Secured guns and authorization

---

code/modules/admin/admin.dm

Для админов ~~чтобы задобрить~~ исправляет сломанную разметку в панели игрока. 
До фикса: 
После фикса:
Также убирал дубликаты кнопки прыжка к игроку иииииии вынес разметку с информацией о клиенте в отельные скобки.

исправление разметки PP

---

code/modules/organs/internal/species/adherent.dm

Даёт возможность перелетать всякие объекты. Сделано по запросу игрока играющего за них

полёт адхерентов над столами

---

code/modules/mob/living/carbon/human/life.dm

Низкое давление перестает наносить урон при достижении лимита, равного ХП моба. То есть вводит в крит.

Никаких гибов в вакууме

---

interface/skin.dmf

Наконец-то дошли руки убрать этот недочёт 😎👍🏻 Можно перенести на оригинал.

удаление неиспользуемой вкладки окна

---

code/datums/movement/mob.dm
code/game/turfs/turf.dm
code/modules/mob/inventory.dm
code/modules/mob/mob.dm

пожалуйста, почитайте предисловие:
Для начала я хочу описать свою позицию по поводу этих изменений.
Я не хочу спорить и разводить срачей, а потом кидать кислую мину, поэтому опишу суть данных изменений, плюсы, минусы.
Грамотно дискуссировать и использовать критическое мышление предлагаю в дискорде проекта, где игрокам будет проще обменяться друг с другом своим мнением.
****
Когда-то у кого-то была речь, а речью было - рука, ну или две. Существовала идея создать возможность брать предметы в руки когда ты лежишь, но идея была сомнительной.
Поэтому тут предлагается внести описанные ниже изменения, которые позволят подбирать предметы лёжа.
Отличительные изменения?
1. Предмет не выпадет, если лечь на пол добровольно.
2. Предмет можно поднять если ты лежишь на полу.
3. Предмет может выпасть, …

взаимодействия лёжа

---

infinity/code/modules/telesci/telesci_computer.dm

В телесайнсе нельзя вводить в качестве сектора число более 15, если ввести больше, то в любом случае будет выбран 15 сектор. В данном реквесте допустимое число для сектора повышено до 25.
Пример:
Сектор планеты:17
Сам сектор разрешен для телепортации, но так как ввести число больше 15 нельзя, то настроить телепад на планету не получится.

Телесайнс. Максимальное значение сектора

---

infinity/code/modules/materials/reciepes.dm

раньше по ошибке вместо металлической колбы крафтилась бронепластина
также невозможно было скрафтить бумажный стаканчик
все это сейчас починил, надеюсь

ремонт майнкрафта

---

code/modules/power/apc.dm

Привет, обнаружил проблему со слоями для APC которые должны были быть поверх слоя света. Вот исправление.

Фикс слоёв для АПЦ

---

infinity/code/game/objects/items/weapons/storage/backpack.dm

Привет, воспользовавшись фидбеком и отзывами я подумал что можно предложить временно отключить данное ограничения для рюкзаков. Функцию оставил т.к. она может пригодиться для каких-то конкретных рюкзаков в будущем.

Временное отключение ограничений рюкзака

---

code/modules/holodeck/HolodeckControl.dm

Привет, в этом пр я сделал простую тёмную тему консоли голодека с помощью "имитации NanoUI" (браузер).
По умолчанию все цвета в таком интерфейсе сливались с фоном, поэтому мне пришлось схитрить и добавить дополнительную проверку для замены всех цветов на более приятные. 
Результат на фотографии ниже:

Простая до ужаса тёмная тема голодека

---

code/game/objects/items/weapons/tanks/tank_types.dm

У двойного баллона с кислородом объем 90.
У двойного с азотом сейчас - 60.
Произошел коммунизм и баллон с азотом тоже стал объемом как кислородный.
Раньше мне казалось что двойной азотный кончается раза в полтора быстрее чем кислородный, оказалось так и есть. Теперь это пофикшено. Надеюсь.

фикс двойного баллона с азотом

---

baystation12.dme
code/modules/integrated_electronics/core/assemblies.dm
code/modules/integrated_electronics/subtypes/manipulation.dm
infinity/code/modules/integrated_electronics/core/assemblies.dm
infinity/code/modules/integrated_electronics/subtypes/manipulation.dm

- Добавлена возможность загружать пИИ и оружие на соответствующие платы без их переподсоединения (по клику на открытый корпус предложит установить на соответствующие платы). 
- Для платы integrated intellegence control добавлено выходящее значение Clicked Ref (референс предмета, по которому кликает пИИ в плате) и активаторы on click, middle click, double click, shift click, ctrl click, alt click, которые отслеживают соответствующие клики пИИ в плате.
- Bluespace rift вновь может открывать порталы по телепортам, а не только рандомные.

Некоторые изменения плат

---

code/modules/surgery/surgery.dm

Позволяет боргам вновь вставлять органы через гриппер. (Ранее была проверка наличия вставляемого предмета в активном слоте, что находило сам gripper, а не орган(как должно быть), что отменяло операцию).

Фикс проверки хирургии для грипперов

---

html/changelogs_infinity/coltrane97-gup.yml
maps/sierra/sierra-1.dmm
maps/sierra/sierra_overmap.dm

UPD
Диффы карты:
Изменил некоторые значения в sierra_overmap.dm:
- Максимальная скорость такая же, как и у харона
- Масса снижена с 2200 тонн до 500 (влияет на просчет ускорения)
- Задержка между ускорениями снижена с двух(2) до половины(0.5) секунды (кулдаун, когда кнопочки серые)
- Скилл необходимый для управления снижен с трейнеда до бейзика
Что касается карты, то:
- Со старта пакман содержит 10 листов вместо пяти
- Слева теперь есть окно, кнопка от створок находится рядом с другой
- APC и алярм теперь воспринимают доступ Гуппи
Если что, чейнджлог есть.

Овермапный гуппи

---

code/modules/integrated_electronics/core/assemblies.dm
code/modules/integrated_electronics/core/integrated_circuit.dm
code/modules/integrated_electronics/subtypes/manipulation.dm
code/modules/integrated_electronics/subtypes/reagents.dm
code/modules/mob/living/silicon/pai/pai.dm
code/modules/surgery/surgery.dm
infinity/code/modules/integrated_electronics/core/assemblies.dm
infinity/code/modules/integrated_electronics/subtypes/manipulation.dm

- пИИ при нажатии collapse chassis нормально отсоединяется от Intelligence control платы.
- Добавлен входящий параметр Instruction для intelligence control module с поддержкой тега br, сюда можно записать, к примеру, инструкцию по управлению, которая будет отображаться для пИИ/ММИ при установке в плату.
- Добавлена возможность вставлять гранату в соответствующую плату через клик по открытому корпусу.
- Добавлена ссылка [Remove Item] в интерфейсе для плат grenade primer, weapon firing mechanism, intelligence control module для быстрого изъятия из них вещей без пересборки. (Появляется только если в плате есть предмет на изъятие - https://prnt.sc/s18zq3).
- Добавлен активатор on push ref для большинства плат связанных с реагентами для упрощения интеракции с ними.
- Добавлена плата floor …

Апдейт плат 2

---

infinity/customs/agrevol.dm

Fixing that damn customka for sure. Тесчено и перетесчено.
Насчет размера - это респрайт rucksack'а, который можно взять за любую профессию. Чтоб он не появлялся в лоадауте у каждого первого аутиста - пришлось перевести его в отдельный подкласс.
Вариант от Лаксеша с подклассом цветного рюкзака почему-то работал на локалке, но не заработал на сервере. I dunno why. Really.

RevolCustomReFix

---

maps/sierra/job/jobs.dm

Это самая первая версия.
Текущая ограничивает следующие:
Главы, АВД, КМ, ЛЭ, старший инженер, старший ученый, вся охрана.
Забавности:
<details>
Резоми:
<details>
</details>
Бустеры:
<details>
</details>
</details>

Ограничение профессий бустеров

---

code/modules/ascent/ascent_rigs.dm
maps/away/ascent/ascent.dm
maps/away/ascent/ascent_jobs.dm
maps/away_inf/ascent/ascent.dm

* Спавн аскентов нужно уменьшить до 1-2 раз в неделю.  - Теперь только админы смогу спавнить их.
* Аскентам нужно дать нормальный не сломанный корабль.  - Думаю админы поймут название, поврежденный колониальный корабль восхождения и обычный, и что спавнить.
* Аскентов следует лишить ригов, или уменьшить им броню для устранения их  
неубиваемости.  - Убрал множитель у рига Алатов и уменьшил показатель брони от лазеров.
* Нужно пофиксить инфу в начале игры  у аскентов, вопреки лору и назначению корабля в самом начале в чате показывается инфа, что их в систему привела ОХОТА, а не колонизационная мисси, следовательно нужно исправить на колонизацию.  - Исправил текст.

Решением главы ксенокома. Снижение возможности автоспавна ахсентов до нуля. Исправление текста ахсентов в начале игры.

---

baystation12.dme
infinity/code/modules/nano/nanoexternal.dm

Аварийная кнопка для клиентов в случае возникновения проблем с окнами NanoUI

Reset NanoUI window button

---

maps/sierra/sierra_ranks.dm

Допиливаем переменные бранчей Сьерры под новый мёрж. Добавляем контракторам и цивилианам возможность делать кастомный email.
Выдаем работникам НТ свой собственный адрес почты "ntmail.corp"

emailingmail

---

code/game/objects/buckling.dm

делает баклинг зависимым от размера мобов
т.е мышь не сможет баклить людей

фикс баклинга

---

code/modules/nano/interaction/base.dm

честно украденная технология запада, адаптированная на русский лад, позволяет снова видеть флаворы из гостоты
одобрено антиерпшерами
это также распространяется на записи и, скорее всего, на оос нотесы

фикс?? чтения флавора из гостоты

---

baystation12.dme
infinity/code/modules/integrated_electronics/subtypes/input.dm

Совсем небольшое изменение к разделу input в виде добавления двух новых плат.
- list pick: доступен как кнопка из интерфейса устройства и позволяет выбрать в виде списка один элемент из загруженного в него листа. Есть два активатора: on pressed - который срабатывает при каждом нажатии и on picked - только при выборе элемента.
- image recognition: по входу и активаторам идентичен плате examiner, но в качестве выхода выдает icon_state выбранной цели.

Небольшое дополнение к интегралкам

---

code/game/objects/buckling.dm

Резоми не могут пристегивать к стульям; данный pull-request изменяет это, не позволяя пристегивать мобов тем, чей mob_size <= MOB_TINY

Фикс баклинга резоми

---

maps/sierra/loadout/loadout_shoes.dm

Теперь в лодауте можно взять лоу воркбуты. Те самые воркбуты, но сексуальнее. Их как минимум три человека просило добавить, но за несколько месяцев это так и не сделали.
Ещё подробнее?
В лодауте появились **low workboots** в разделе **Shoes and Footwear**. Стоят они, к слову, всего один поинт лодаута.

Добавляем Low Workboots в лодаут

---

code/game/machinery/kitchen/microwave.dm

Сообщения действия гаечного ключа isWrench(O) на микроволновку вызывали неправильное действие. Сначала закручивали (вместо откручивали):
The [user] begins [anchored ? "secures" : "unsecures"] the microwave.
You attempt to [anchored ? "secures" : "unsecures"] the microwave.
Баг решен, заменой тернарной функции на адекватную, и правильную. В первом случае  [anchored ? "unsecures" : "secures"] потом [anchored ? "secures" : "unsecures"]

Фикс сообщений

---

code/modules/hydroponics/seed.dm

[За помощь спасибо Skonoplich-y]
Фикс генерации названий мутировавших растений. Изначально названия для мутантов хранились в контроллере SSPlants который задавал имя посредством считывания списка всех семян как их сумму + 1, то же самое делалось и для процедурно-генерируемых. При создании семячки получалось две копии имени, и после того как плод запихивали в сид экстрактор он выдавал семечку процедурно-генерируемого (изначального семени имя которого первым хранилось в списке). Ошибка вышла из-за невнимательности кодеров бея12. Заметить сложно, за что спасибо выше сказанному человеку.

Фикс мутаций ксеноботаники

---

maps/away/voxship/voxship.dm

Эта авейкарта была удалена с актуального бэя. В наших же реалиях своей огромной стоимостью она буквально выжигает другие авейки, cost у которых обычно варьируется от 0,5 до 1. Думаю после этого должно быть понятно, в какую пустыню превращается овермап после появления этого недоразумения. 
Я понимаю, что удаляются авейкарты не так, но мои попытки вырезать его полностью привели только к огромному числу ошибок. Пример подобного "фикса" увидел в нашем коде, как бы, почему нет.
:cl:
bugfix: Убрал спавн VoxBase из авеек
/:cl:

Убираем из спавна Vox Base

---

maps/away_inf/bearcat/bearcat-1.dmm
maps/away_inf/bearcat/bearcat-2.dmm

Поправил доступ в апцешке и эирлоке что были пропущены в первый раз. Ну и немного пошалил на карте спавнером.
:cl:
bugfix: зафикшен доступ к airalarm и APC
maptweak: добавлена всякая мелочевка, пинцет, нагреватель и охладитель, пораспихивал пару ложек/вилок в разные места
maptweak: заменил ломающуюся надувную стенку на шлюз
/:cl:

Bearcat map fixing

---

maps/sierra/job/jobs.dm

По какой-то причине синтетические-кристаллические единицы могли занимать только должности ассистентов и стажеров, за исключением инженерного отдела, что банально смешно.
Так же по какой-то причине работы инженера и медика ЭК были закрыты для адхерантов.
Такое мнение взялось не с пустого места, на Факеле часовые имели доступ ко всем этим отделам и профессиям и даже пилоту, к сожалению у нас пилот занимается командованием и адхеранту подобную процессию не доверить.
P S Это старое описание ПРа, по итогам были добавлены профы карготехника и филд инженера, вот и весь ПР
:cl:
balance: Доступные адхерантам работы изменены. 
/:cl:

Adherent job

---

code/__defines/culture.dm

:cl:
bugfix: Теперь при настройке персонажа вы выбираете не его место проживания, а его место рождения, как и подразумевалось при создании.
/:cl:

Homeworld upd

---

infinity/code/game/machinery/vending.dm

Недавно был обнаружен баг в раздаточных автоматах Сьерры, которые установлены в раздевалке инженеров, складе материалов РНД и общем складе инструментов на третьей палубе.
Проблема была в том, что в автомате лежали аккумуляторы `/obj/item/cell` , у которых было следующее:
```dm
/obj/item/cell/Initialize()
. = ..()
if(type == /obj/item/cell)
crash_with("Invalid use of cell base type")
return INITIALIZE_HINT_QDEL
if(isnull(charge))
charge = maxcharge
update_icon()
```
:cl:
bugfix: Исправлен баг, связанный с тем, что некоторые автоматы не выдавали аккумуляторы.
/:cl:

Исправляем баг с аккумуляторами и вендорами

---

infinity/code/datums/uplink/armor.dm
infinity/code/datums/uplink/devices and tools.dm
maps/antag_spawn/mercenary/mercenary_base_inf.dmm

Описание
=======
После мержа у наёмников и предателей пропали следующие предметы: 
* Набор тяжёлой брони
* Плата для консоли телепорта
Данный пулл-реквест возвращает предметы обратно в аплинк. 
После мержа конструкция телепорта изменилась из-за чего "рамка" телепорта исчезла с корабля наёмников "Десперадо". В виду того, что к подрывникам возвращается возможность купить плату консоли телепорта, на десперадо появляется телепорт-пад, благодаря которому наёмники смогут воспользоваться телепортацией для проникновения на объект.
Скриншоты ниже - телепорт на Десперадо до мержа и телепорт на Десперадо в пулл-реквесте.
На Десперадо была обнаружена следующая проблема: автоматическая заглушка трубы пыталась связаться одновременно с регулятором давления и синей трубой для подачи воздуха. Так как …

Возврат платы платы телепорта и брони наёмникам. Мапперские поправки по базе наёмников. 

---

infinity/code/game/machinery/vending.dm
maps/sierra/areas/multideck.dm
maps/sierra/areas/sierra3.dm
maps/sierra/job/access.dm
maps/sierra/job/jobs_engineering.dm
maps/sierra/job/jobs_exploration.dm
maps/sierra/job/outfits.dm
maps/sierra/sierra-1.dmm
maps/sierra/sierra-2.dmm
maps/sierra/sierra-3.dmm
maps/sierra/sierra_shuttles.dm
maps/sierra/structures/closets/armory.dm
maps/sierra/structures/closets/engineering.dm
maps/sierra/structures/closets/exploration.dm

Данный пулл-реквест направлен на работу с картой и взаимодействие игроков с ней. Что-то появилось, что-то исчезло, что-то просто изменилось. Список будет большим.
---
Декали, которые используются для выделения зелёного уголка очень сильно выделяются и не вписываются в общую палитру помещения. Теперь угол не будет так ярко выделен.
Очень вероятно, что автомат с отравленной едой попал в общую зону по ошибке. Во избежание роста смертности лысых ассистентов и чайных трапов было решено заменить этот автомат на автомат с кофе.
---
В ходе переработки мостика была допущена ошибка в виде стен, что появлялись пол некоторыми окнами мостика. Теперь этих стен более не должно быть.
Тоже самое, что и стены - голоцветов под машинерией на мостике быть не должно
Офицеры Брига получили доступ к помещению …

Большие изменения по карте

---

maps/sierra/job/jobs_security.dm

Также заместо младшего охранника введен рекрут охраны на случай, если игрок будет заинтересован в отыгрыше совсем "зелёного" офицера, который только-только был допущен к работе в отделе службы безопасности.

Перемещение Junior Guard в подпрофессию офицера

---

code/game/machinery/robotics_fabricator.dm

раньше фабрикатор в роботике не принимал в себя материал (титан) но после включения пары строчек случилось следующее:
🆑
bugfix: Фабрикатор теперь может принимать в себя листы титана.
/🆑

bugfix robotics_fabricator

---

code/game/antagonist/outsider/mercenary.dm

Недавно выяснилось, что у лидера наёмников плохая память, и когда команда уже собирается выполнять свою миссию, чтобы получить денюжки от ~~Зенг-ху~~ неизвестного заказчика, лидер в самый последний момент забывает код!
Данный пулл-реквест должен прописать таблетки лидеру наёмников и теперь при старте раунда он будет помнить код бомбы.
:cl:
bugfix: Наёмники: Лидер Наёмников снова знает код от бомбы. Чтобы узнать - используйте "Check Notes" во вкладке "IC"
/:cl:

Вбиваем в голову лидера мерков код от системы самоуничтожения

---

maps/sierra/loadout/loadout_tactical.dm

Дарим возможность всем желающим зайти в военторг и взять боевую рубаху(прямо как камуфляжный костюмчик для леса), которая не имеет каких-либо защитных свойств. Этот буллщит носит 0.5 человека в охране и ЭК, а так, может, станет популярнее

УБАКи для всех

---

maps/sierra/datums/supplypacks/security.dm

Данный ПР переносит заказ в карго на ящик NT41 из доступных в синий код заказов в доступные по красному коду заказы за счёт своей смертоносности.
:cl:
balance: Заказать в карго ящик НТ41 можно теперь только во время Красного Кода.
/:cl:

Меняем требование к заказу ящика NT41 с синего на красный

---

infinity/customs/asriel.dm
infinity/customs/wolforbykot.dm
maps/away_inf/sentinel/sentinel_items.dm

Данный пулл-реквест снова трогает кастомки, а также одежду Сентинеля.
* Кастомка Азриеля - исправлена опечатка
* Кастомка Вольфора и КО - разгрузка не будет исчезать при проке "roll down"
* Сентинель - утилити-униформа не теряет спрайты (Ту самую, что носят техники и медики)

Исправления кастомок + Фикс одежды Сентинеля

---

maps/away_inf/liberia/liberia.dm
maps/away_inf/liberia/liberia.dmm
maps/away_inf/liberia/liberia_navpoints.dm
maps/sierra/sierra_shuttles.dm

Данный пулл-реквест направлен на исправления на авей-карте "Либерия".  В основном ориентир был на один из последних репортов:
* Добавлено 5 новых нав-поинтов (4 точки для всех с каждой стороны света + 1 точка для ниндзи)
* Кнопки и контроллеры на шлюзах у солнечных панелей исправлены и теперь могут быть дополнительными точками входа или выхода Либерии
* Бесполезная консоль  управления шаттлом в офисе торговцев заменена на стол
* Пол под сенсорами Либерии заменён на тот, что имеет при себе воздух. Теперь Торговцам необходимо открывать створку для запуска сенсоров
* Изменён пол под турбинами Мула. Теперь там изначально не будет находиться "пол с воздухом", что создавало ранее "активные углы"
:cl:
maptweak: Либерия: добавлено 5 новых нав-поинтов. 4 общих и 1 для антагониста.
maptweak: …

Исправления на Либерии

---

maps/away_inf/sentinel/sentinel_items.dm
maps/torch/items/clothing/solgov-under.dm

Данный пулл-реквест должен исправить отображение военной униформы.
Во время последних мержей были неверно переуказаны названия спрайтов униформы Флота
Если заглянуть в файл, откуда берутся спрайты, то можно заметить, что названия у спрайтов действительно другие
А на Бее как раз указаны правильные названия используемых спрайтов
:cl:
bugfix: Исправлено отображение спрайтов униформы Флота
/:cl:

[Факел] Исправление военной униформы

---

code/game/objects/items/robot/robot_items.dm
code/modules/mob/living/silicon/robot/modules/module_research.dm

Добавил научному боргу научный худ для сканирования объектов на наличие технологий. До этого наличие технологий на борге можно было узнать только после разборки, что усложняет процесс исследований и делает реверс-инженеринг неэффективным.
🆑
rscadd: Научному боргу добавлен специальный HUD учёных
/🆑

Добавление Science HUD для научного борга

---

code/game/objects/items/passport.dm
maps/sierra/items/items.dm
maps/sierra/loadout/loadout_xeno.dm

:cl:
rscadd: Добавлен паспорт ЦПСС для Колхиса, паспорта Эремуса и А`шранды, а также ксенопаспорт для Унати.
/:cl:

Добавление паспортов и ксенодокументов

---

maps/sierra/loadout/loadout_accessories.dm
maps/sierra/loadout/loadout_ec_skillbages.dm

Знаки отличия и повязки теперь доступны обычным обывателям, а не как раньше только для ЭК
:cl:
tweak: Теперь значок пилота и повязки требуют не должности, а навыков
/:cl:
close #2222

Значки и повязки

---

maps/sierra/sierra-4.dmm

:cl:
bugfix: Стулья в комнате совещаний голодека стали голограммой, не позволяя разбирать их на металл.
/:cl:

Фикс дюпа металлов с голодека

---

code/controllers/subsystems/jobs.dm
code/modules/client/preferences_spawnpoints.dm
infinity/code/datums/spawnpoints/cryo/effects.dm

Данный пулл-реквест направлен на сокращение времени ожидания игроков пробуждения их персонажей как во время старта игры так и во время позднего захода в игру. 
* Во время раундстартового пробуждения персонажи будут спать не 15, а 3 секунды.
* Во время пробуждения из крио глаза персонажа не будут покрываться пеленой, а скорость передвижения понижаться (не касается "особых" случаев пробуждения).
* Во время пробуждения из крио  персонажа не будет кидать в сон через несколько секунд после захода в раунд.
* Шанс заработать особый эффект пробуждения с описанием "Трясёт от холода." снижен до 10-ти процентов.

Делаем раундстартовое пробуждение и пробуждение из крио менее раздражительным

---

code/game/objects/items/weapons/storage/med_pouch.dm
code/modules/reagents/reagent_containers/hypospray.dm
infinity/code/modules/reagents/reagents_containers/hypospray.dm

Фикс отображения цветовой маркировки у инжекторов
Все инжекторы уже черт знает сколько времени имеют синюю маркировку вне зависимости от содержимого, так быть не должно.
Главная проблема была в некорректной ссылке на иконку старых инжекторов с заранее прорисованной маркировкой, пофиксил путь до правильного спрайта и заменил цвета из палитры на цвет самого химиката. Цвета палитры слишком темные для отображения на маркировочной ленте. Например, дексалин не отличить от ино.
В принципе, мне не принципиально какой именно будет цвет у инжекторов, мне главное чтобы они отличались между собой.
:cl:
bugfix: Фикс полос у инжекторов. Теперь они маркированы цветом своего препарата.
/:cl:

Autoinjector band color fix

---

infinity/code/modules/species/station/lizard.dm

В этом пулл-реквесте Erosan унати получают флаг `SPECIES_IS_RESTRICTED` из-за которого выбрать их в редакторе персонажа нельзя, как и заспавниться без помощи администраторов.

Добавляем Erosan-ящерам флаг SPECIES_IS_RESTRICTED

---

maps/sierra/sierra-2.dmm

Была разобрана пристройка где раньше стояли игровые автоматы
* Перестановка игровой зоны, так же некоторые переработки в новых дормиториях
* некоторым игрокам не нравилась "неоднородность" Дорм
*Убрана "пристройка" 
* Мелкие правки новых дорм
* Перемещена игровая зона, теперь выглядит более "эргономично"

Переработка игровой зоны в новых дормиториях

---

maps/sierra/sierra-2.dmm
maps/sierra/sierra-3.dmm

Данный пулл-реквест слегка изменяет интерьер на второй палубе, убирая мешающие гирлянды и неуместную ёлку во вторых дормиториях. Добавляются ресурсы в научный отсек.
* Гирлянды в баре теперь не будут висеть над барной стойкой, мешая тем самым раскладывать предметы и напитки
* Заделан угол на кухне, на месте которого стоял стол с микролатом. Сам микролат теперь находится у рояла.
* В научном отсеке увеличены стартовые запасы стали, стекла, пластика и аллюминия 
* Добавьте сюда скриншоты
* Это опционально, но помогает оценить результат работы
* Не забывайте добавлять скриншотам примечания, если их много
* Если Вы хотите сделать сравнение между двумя скриншотами - можете воспользоваться таблицей
* В ином случае можете её убрать и просто оставлять скриншоты
:cl:
maptweak: Увеличены запасы …

Ресурсы в РНД, небольшие косметические правки

---

maps/sierra/sierra-2.dmm
maps/sierra/structures/closets/exploration.dm

Полевому инженеру подарили второй вид перчаток, а из душевых убрана камера для подглядыванием за людьми в душевых.
:cl:
rscadd: В шкаф полевого инженера добавлены изоляционные перчатки.
maptweak: Камеры из душевых вторых дорм полностью убраны.
/:cl:

Изоляционки полевому инженеру, ликвидация камеры из душевой вторых дорм

---

maps/sierra/sierra-1.dmm

Фиксим декали. Вешаем обратно новогодние фонарики
Ну короче. Меня обоссал Элар за мой говномапинг в карго. Заставил доделывать. Я добавил декали так, чтобы не было кринжа. Плюс повесил обратно новогодние лампочки и фанфары на двери и вернул на стены, где они были ~(пойду уберу новогоднюю елку обратно в подвал)~. Скрины вкидывать мне лееень, ибо значительного видимого результата нет. 
Поэтому держите кошкодевочку
:cl:
maptweak: поправлены декалы в карго. Теперь они выглядят кошерно.
maptweak: Новогодние конфетти повешены обратно.
/:cl:

decale fixing
